apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service-config # ALTERAR
  namespace: techchallenge
data:
  # Database
  SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate

  # JWT Expiration
  JWT_ACCESS_TOKEN_EXPIRATION: "900000"
  JWT_REFRESH_TOKEN_EXPIRATION: "604800000"