apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-admin-service # ALTERAR
  namespace: techchallenge
  labels:
    app: tech-challenge-admin-service # ALTERAR
spec:
  selector:
    app: tech-challenge-admin-service # ALTERAR
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP